name: AUREN AUTO GOLD

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  run-auren-gold:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GROQ_MODEL: "llama-3.3-70b-versatile"
      AUREN_HUB_SPACE_ID: "Mariapc601/AUREN-API-HUB"
      AUREN_CREATIVE_SPACE_ID: "Mariapc601/AUREN-CREATIVE-ENGINE"
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AUREN AUTO GOLD script
        run: |
          python auto_gold.py

